# Generated by Django 4.2.6 on 2023-10-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_rename_name_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
